for all datasets

In [8]:
import pandas as pd
df_loan = pd.read_csv("C:/Users/admin/Downloads/datasets/loan_portfolio_dataset.csv")

In [9]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 61.0 MB

In [10]:
import numpy as np

conditions = [
    (df_loan['tenure_months'] >= 0) & (df_loan['tenure_months'] <= 1),
    (df_loan['tenure_months'] > 1) & (df_loan['tenure_months'] <= 3),
    (df_loan['tenure_months'] > 3) & (df_loan['tenure_months'] <= 6),
    (df_loan['tenure_months'] > 6) & (df_loan['tenure_months'] <= 12),
    (df_loan['tenure_months'] > 12)
]

choices = [
    '0-30 Days',
    '30-90 Days',
    '90-180 Days',
    '6M-1Y',
    '1Y+'
]
df_loan['alm_bucket'] = np.select(conditions, choices, default='unknown')

In [11]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
 10  alm_bucket             800000 non-null  str
dtypes: float64(1), int64(4), str(6)
memory usage: 67.1 MB

In [5]:
df_loan['alm_bucket']

0         1Y+
1         1Y+
2         1Y+
3         1Y+
4         1Y+
         ...
799995    1Y+
799996    1Y+
799997    1Y+
799998    1Y+
799999    1Y+
Name: alm_bucket, Length: 800000, dtype: str

In [27]:



loan_exp = df_loan['outstanding_principal']

In [28]:
loan_exp

0         1399755
1         1509414
2         3963945
3         3933227
4         1414890
           ...
799995    1827723
799996    3717405
799997    1035235
799998     572950
799999    1629175
Name: outstanding_principal, Length: 800000, dtype: int64

In [14]:
import pandas as pd
df_borr = pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [15]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.7 MB

In [16]:
df_borr['borrowing_amount'] = pd.to_numeric(df_borr['borrowing_amount'], errors='coerce')
df_borr['maturity_bucket'] = df_borr['maturity_bucket'].str.lower().str.strip()

borr_exp = df_borr.groupby('maturity_bucket', as_index=False)['borrowing_amount'].sum()
borr_exp = borr_exp.rename(columns={
    'maturity_bucket': 'alm_bucket',
    'borrowing_amount': 'borrowing_exposure'
})

In [17]:
df_borr

,borrowing_id,funding_source,cost_of_funds,maturity_bucket,interest_reset_type,borrowing_amount,rollover_risk_score
0,1,NCD,9.07,6m,Floating,8928717,0.9472
1,2,Term Loan,8.69,6m,Floating,31344155,0.2102
2,3,Bank Line,7.46,6m,Floating,21925818,0.3430
3,4,NCD,8.45,3y,Floating,11737224,0.9142
4,5,NCD,7.56,3y,Fixed,43446206,0.6087
...,...,...,...,...,...,...,...
199995,199996,Term Loan,5.65,3y,Floating,18949628,0.6378
199996,199997,Bank Line,9.38,3m,Fixed,10606928,0.0016
199997,199998,Commercial Paper,9.39,3m,Fixed,33548319,0.5925
199998,199999,NCD,5.33,3m,Fixed,44607877,0.0913
199999,200000,Term Loan,9.93,3m,Floating,14007877,0.4326

In [18]:
borr_exp

  alm_bucket  borrowing_exposure
0         1m       1018769851381
1         1y       1023566934659
2         3m       1018281640413
3         3y       1016408499246
4         6m       1016733602995

In [ ]:
df_alm_gap = df_loan['Loan_Exp'] - df_borr['Borr_Exp']